language: java

sudo: required

services:
  - mysql
  - postgresql

jdk:
  - oraclejdk9
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  - MAVEN_SKIP_RC=true TRAVISBUILD=true

after_success:
  - mvn -P travis,!dev jacoco:report coveralls:report


before_install:
  - echo "127.0.0.1    $HOSTNAME" | sudo tee -a /etc/hosts
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get -y update
  - sudo apt-get -y install oracle-java9-installer

before_script:
  - mysql -e 'create database sfm;'
  - psql -c 'create database sfm;' -U postgres