language: java

sudo: required
dist: trusty

services:
  - postgresql

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

matrix:
  include:
    - jdk: oraclejdk8
      script:  mvn test javadoc:javadoc -B && mvn -P travis,!dev -DserviceName=travis-ci jacoco:report coveralls:report
    - jdk: oraclejdk9
      install: . ./.travis/install-jdk-9.sh
      script:  mvn test -B
    - jdk: openjdk7
      script:  mvn test javadoc:javadoc -B    
      install: . ./.travis/install-jdk-7.sh
    - jdk: openjdk6
      script:  mvn test javadoc:javadoc -B
      install: . ./.travis/install-jdk-6.sh
    - script:  mvn test -B
      install: . ./.travis/install-jdk-10.sh
    

env:
  - MAVEN_SKIP_RC=true TRAVISBUILD=true

before_install:
  - echo "127.0.0.1    $HOSTNAME" | sudo tee -a /etc/hosts
  - wget https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip
  - unzip -qq apache-maven-3.2.5-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.2.5
  - export PATH=$M2_HOME/bin:$PATH

  
before_script:
  - mysql --verbose -u root -e 'create database sfm;'
  - mysql --verbose -u root -e "CREATE USER 'sfm'@'localhost';"
  - mysql --verbose -u root -e "GRANT ALL ON sfm.* TO 'sfm'@'localhost';"
  - psql -c 'create database sfm;' -U postgres
