language: java

sudo: required
dist: trusty
group: edge

services:
  - postgresql

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

jdk:
  - oraclejdk9
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  - TRAVISBUILD=true
  - MAVEN_SKIP_RC=true

after_success:
  - mvn -P travis,!dev jacoco:report coveralls:report


before_install:
  echo "127.0.0.1    $HOSTNAME" | sudo tee -a /etc/hosts

before_script:
  - mysql -u root -e 'create database sfm;'
  - psql -c 'create database sfm;' -U postgres
