language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  - TRAVISBUILD=true

after_success:
  - mvn -P travis,!dev jacoco:report coveralls:report


before_install:
    echo "127.0.0.1    $HOSTNAME" | sudo tee -a /etc/hosts