language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  - 

after_success:
  - mvn -P travis jacoco:report coveralls:report


before_install:
    echo "127.0.0.1 "hostname | sudo tee /etc/hosts